### PR TITLE
Move to module

### PR DESCRIPTION
**Pull request by matteobachetti**
This should fix the merge issues with Scott's master

### CODE REVIEW

**Comment by matteobachetti** [comment]
@gijzelaerr have you seen this?

**Comment by gijzelaerr** [comment]
ah! no, i missed that thanks. lemmie see.

**Comment by gijzelaerr** [comment]
Ok i don't have too much time to look into this now, but it looks ok to me. If only we had some proper test set :)

Do you think I can just merge it? 

I'm not sure if you are using the KERN packages, but i'll update KERN later this year and bundle it with this modified presto.

**Comment by matteobachetti** [comment]
If @scottransom hasn't made any conflicting commits in the meantime, it should be good to go!

**Comment by gijzelaerr** [comment]
ok then i trust your judgement! Thanks!

**Pull request merged**
